export const CASE_STATUS = {
    STARTED: "STARTED",
    DIVORCE_FORM_COMPLETED: "DIVORCE_FORM_COMPLETED",
    RESOLUTION_SUCCESS: "RESOLUTION_SUCCESS",
    RESOLUTION_FAILED: "RESOLUTION_FAILED",
    AGREEMENT_COMPLETED: "AGREEMENT_COMPLETED",
    AFFIDAVITS_COMPLETED: "AFFIDAVITS_COMPLETED",
    UNDER_REVIEW: "UNDER_REVIEW",
    APPROVED: "APPROVED",
  };
  